from calculos import META_PRESSAO, calcular_media, calcular_variancia, calcular_desvio_padrao, calcular_amplitude, calcular_porcentagem, diagnostico_turno, diagnostico_geral, descrever_desvio_meta

def exibir_metricas_parciais(cont, media, menor_pressao, maior_pressao, amplitude, desvio_padrao, zona_verde, zona_amarela, zona_vermelha, mudancas_zona, picos_vermelhos_isolados):
    porcentagem_verde = calcular_porcentagem(zona_verde, cont)
    porcentagem_amarela = calcular_porcentagem(zona_amarela, cont)
    porcentagem_vermelha = calcular_porcentagem(zona_vermelha, cont)
    diagnostico = diagnostico_turno(0, zona_vermelha, mudancas_zona)

    print("\n=======================================================")
    print("               MÉTRICAS PARCIAIS DO TURNO")
    print("=======================================================")
    print(f"  Quantidade de pressões lidas : {cont}")
    print(f"  Média das pressões ajustadas : {media:.2f} UPCs")
    print(f"  Menor pressão ajustada       : {menor_pressao:.2f} UPCs")
    print(f"  Maior pressão ajustada       : {maior_pressao:.2f} UPCs")
    print(f"  Amplitude (maior - menor)    : {amplitude:.2f} UPCs")
    print(f"  Desvio padrão                : {desvio_padrao:.2f} UPCs")
    print(f"  Pressão alvo (meta)          : {META_PRESSAO} UPCs")
    print(f"  {descrever_desvio_meta(media)}")
    print("-------------------------------------------------------")
    print(f"  Zona Verde    : {zona_verde} leituras ({porcentagem_verde:.2f}%)")
    print(f"  Zona Amarela  : {zona_amarela} leituras ({porcentagem_amarela:.2f}%)")
    print(f"  Zona Vermelha : {zona_vermelha} leituras ({porcentagem_vermelha:.2f}%)")
    print(f"  Picos vermelhos isolados : {picos_vermelhos_isolados}")
    print("-------------------------------------------------------")
    print(f"  Diagnóstico   : {diagnostico}")
    print("=======================================================")

def exibir_metricas_turno(menor_pressao, maior_pressao, media, amplitude, desvio_padrao, percentual_leituras, houve_travamento, encerramento_antecipado, zona_verde, zona_amarela, zona_vermelha, mudancas_zona, picos_vermelhos_isolados):
    total_leituras_turno = zona_verde + zona_amarela + zona_vermelha
    porcentagem_verde = calcular_porcentagem(zona_verde, total_leituras_turno)
    porcentagem_amarela = calcular_porcentagem(zona_amarela, total_leituras_turno)
    porcentagem_vermelha = calcular_porcentagem(zona_vermelha, total_leituras_turno)
    diagnostico = diagnostico_turno(houve_travamento, zona_vermelha, mudancas_zona)

    print("\n=======================================================")
    print("                  MÉTRICAS DO TURNO")
    print("=======================================================")
    print(f"  Quantidade de pressões lidas : {total_leituras_turno}")
    print(f"  Média das pressões ajustadas : {media:.2f} UPCs")
    print(f"  Menor pressão ajustada       : {menor_pressao:.2f} UPCs")
    print(f"  Maior pressão ajustada       : {maior_pressao:.2f} UPCs")
    print(f"  Amplitude (maior - menor)    : {amplitude:.2f} UPCs")
    print(f"  Desvio padrão                : {desvio_padrao:.2f} UPCs")
    print(f"  Pressão alvo (meta)          : {META_PRESSAO} UPCs")
    print(f"  {descrever_desvio_meta(media)}")
    print("-------------------------------------------------------")
    print(f"  Zona Verde    : {zona_verde} leituras ({porcentagem_verde:.2f}%)")
    print(f"  Zona Amarela  : {zona_amarela} leituras ({porcentagem_amarela:.2f}%)")
    print(f"  Zona Vermelha : {zona_vermelha} leituras ({porcentagem_vermelha:.2f}%)")
    print(f"  Picos vermelhos isolados : {picos_vermelhos_isolados}")
    print("-------------------------------------------------------")
    if houve_travamento == 1:
        print(f"  Leituras realizadas : {percentual_leituras:.2f}% do turno (TRAVAMENTO)")
    elif encerramento_antecipado == 1:
        print(f"  Leituras realizadas : {percentual_leituras:.2f}% do turno (ENCERRADO ANTECIPADAMENTE)")
    else:
        print("  Sistema encerrado sem travamento")
    print(f"  Diagnóstico         : {diagnostico}")
    print("=======================================================")

def exibir_metricas_totais(total_turnos, total_leituras, menor_pressao_global, maior_pressao_global, total_soma_pressoes, total_soma_quadrados, total_travamentos, total_encerramentos_antecipados, total_zona_verde, total_zona_amarela, total_zona_vermelha, total_mudancas_zona, total_picos_isolados):
    media_geral = calcular_media(total_soma_pressoes, total_leituras)
    variancia_geral = calcular_variancia(total_soma_quadrados, media_geral, total_leituras)
    desvio_geral = calcular_desvio_padrao(variancia_geral)
    amplitude_geral = calcular_amplitude(maior_pressao_global, menor_pressao_global)
    porcentagem_verde_geral = calcular_porcentagem(total_zona_verde, total_leituras)
    porcentagem_amarela_geral = calcular_porcentagem(total_zona_amarela, total_leituras)
    porcentagem_vermelha_geral = calcular_porcentagem(total_zona_vermelha, total_leituras)
    diagnostico = diagnostico_geral(total_travamentos, total_zona_vermelha, total_mudancas_zona)

    print("\n=======================================================")
    print("                   MÉTRICAS TOTAIS")
    print("=======================================================")
    print(f"  Total de turnos realizados   : {total_turnos}")
    print(f"  Total de leituras realizadas : {total_leituras}")
    print(f"  Média geral das pressões     : {media_geral:.2f} UPCs")
    print(f"  Menor pressão global         : {menor_pressao_global:.2f} UPCs")
    print(f"  Maior pressão global         : {maior_pressao_global:.2f} UPCs")
    print(f"  Amplitude global             : {amplitude_geral:.2f} UPCs")
    print(f"  Desvio padrão global         : {desvio_geral:.2f} UPCs")
    print(f"  Pressão alvo (meta)          : {META_PRESSAO} UPCs")
    print(f"  {descrever_desvio_meta(media_geral)}")
    print("-------------------------------------------------------")
    print(f"  Zona Verde    : {total_zona_verde} leituras ({porcentagem_verde_geral:.2f}%)")
    print(f"  Zona Amarela  : {total_zona_amarela} leituras ({porcentagem_amarela_geral:.2f}%)")
    print(f"  Zona Vermelha : {total_zona_vermelha} leituras ({porcentagem_vermelha_geral:.2f}%)")
    print(f"  Picos vermelhos isolados : {total_picos_isolados}")
    print("-------------------------------------------------------")
    print(f"  Turnos com travamento            : {total_travamentos}")
    print(f"  Turnos encerrados antecipadamente: {total_encerramentos_antecipados}")
    print(f"  Diagnóstico geral                : {diagnostico}")
    print("=======================================================")
