def tela_inicializacao():
    print("\n=======================================================")
    print("       SISTEMA DE MONITORAMENTO DE PRESSÕES")
    print("         Refinaria Delta-9  |  SEUC-4")
    print("=======================================================")
    print("  Bem-vindo ao Painel Operacional do DPE")
    print("  -------------------------------------------------------")
    print("  Este sistema realiza o monitoramento e ajuste de")
    print("  pressões industriais por turno de operação,")
    print("  classificando cada leitura nas zonas de")
    print("  estabilidade operacional:")
    print("  -------------------------------------------------------")
    print("  Zona Verde    :  120 a 180 UPCs  (pressão estável)")
    print("  Zona Amarela  :  fora do padrão  (ate 250 UPCs)")
    print("  Zona Vermelha :  pressão crítica (acima de 250 UPCs)")
    print("  -------------------------------------------------------")
    print("  O sistema emite alertas ao detectar pressão crítica")
    print("  e aciona o Protocolo de Travamento ao identificar")
    print("  duas leituras consecutivas na zona vermelha.")
    print("  -------------------------------------------------------")
    print("  Adicionalmente, o sistema oferece métricas detalhadas")
    print("  em três níveis de visualização:")
    print("")
    print("  Parciais  :  acompanhamento em tempo real do turno")
    print("  Por turno :  resumo completo ao fim de cada turno")
    print("  Totais    :  consolidado de todos os turnos da sessão")
    print("")
    print("  Todas as métricas incluem contagem e porcentagem por")
    print("  zona, pressões extremas, média geral e diagnóstico")
    print("  automático da estabilidade operacional.")
    print("=======================================================")
    input("  Pressione Enter para acessar o painel operacional...")

def tela_creditos():
    print("\n=======================================================")
    print("                      CRÉDITOS")
    print("=======================================================")
    print("  -------------------------------------------------------")
    print("  Desenvolvido por:")
    print("  -------------------------------------------------------")
    print("  Felipe Piva              RA: 26006616")
    print("  Leonardo Varela          RA: 26000370")
    print("  Rafael Jorge             RA: 26000459")
    print("  Vinicius Baiocco         RA: 26009531")
    print("  -------------------------------------------------------")
    print("  Disciplina : ALGORITMOS DE PROGRAMAÇÃO, PROJETOS E COMPUTAÇÃO")
    print("  Turma      : T0102")
    print("=======================================================")
    input("  Pressione Enter para voltar ao menu...")

def menu_inicial(sistema_inicializado):
    print("\n=======================================================")
    print("   SEUC-4 | Refinaria Delta-9 | Tela de Acesso")
    print("=======================================================")
    if sistema_inicializado == 0:
        print("\n1 - Inicializar Sistema")
    else:
        print("\n1 - Retomar Operação")
    print("2 - Créditos")
    print("3 - Sair")

def menu_secundario():
    print("\n=======================================================")
    print("SEUC-4 | Refinaria Delta-9 | Painel Operacional do DPE")
    print("=======================================================")
    print("\n1 - Começar Novo Turno")
    print("2 - Mostrar Métricas do Turno Atual")
    print("3 - Mostrar Métricas Totais")
    print("4 - Voltar à Tela de Acesso")
    print("5 - Resetar Sessão (zerar todos os totais)")

def menu_pressoes():
    print("\n-------------------------------------------------------")
    print("1 - Inserir pressão")
    print("2 - Métricas Parciais do Turno")
    print("3 - Encerrar turno antecipadamente")

def menu_review_travamento():
    print("\n=======================================================")
    print(" SEUC-4 | Refinaria Delta-9 | Revisão de Travamento")
    print("=======================================================")
    print("\n1 - Analisar causa do travamento")
    print("2 - Mostrar métricas do turno interrompido")
    print("3 - Voltar ao painel operacional")
